name: tbpweb-dev
dependencies:
  - python=3.9
  - pip
  - pip:
    - -r requirements.txt
    - pre-commit==1.14.4
    - pytest==4.3.0
    - pytest-django==3.4.7
    - tox==3.7.0
    - livereload==2.6.0
    # - coverage[toml]==6.3.2
    # - black==22.3.0
variables:
  TBPWEB_MODE: "dev"
  DJANGO_SETTINGS_MODULE: "settings"
  DJANGO_WSGI_MODULE: "settings.wsgi"
